extends CharacterBody3D
##
## Template for auto-generated player controllers.
##
## The plugin copies this file when generating a new AnimationTree system,
## injecting the scene's actual animation state names into the available_states
## array (replacing the placeholder), then saves it to AnimTreeList/PlayerController.gd.
##
## Features (all configurable in the inspector):
##  - Mouse‑look camera (toggle capture with Escape)
##  - Jump with wind‑up prep delay (1.9s default)
##  - Slide on double‑tap crouch while running (5s cooldown)
##  - Smooth blend‑space transitions
##  - Per‑axis movement/camera inversion flags
##  - Attack, block, dodge combat states
##
## Node requirements:
##  - An AnimationTree child node (auto‑found via find_child)
##  - A Camera3D child node for mouse look (auto‑found via find_child)

@onready var animation_tree: AnimationTree = find_child("AnimationTree") as AnimationTree
@onready var state_machine = animation_tree.get("parameters/playback")
@onready var camera: Camera3D = find_child("Camera3D") as Camera3D

# --- Inspector parameters ---
@export_group("Movement Parameters")
@export var speed: float = 5.0
@export var run_speed_multiplier: float = 2.0
@export var crouch_speed_multiplier: float = 0.5
@export var jump_force: float = 12.0
@export var gravity: float = 20.0
@export var blend_speed: float = 8.0

@export_group("Mouse & Camera")
@export var mouse_sensitivity: float = 0.002
@export var invert_mouse_x: bool = false
@export var invert_mouse_y: bool = false

@export_group("Inversion")
@export var invert_move_x: bool = false
@export var invert_move_z: bool = false

# --- Runtime state flags ---
var is_moving: bool = false
var is_running: bool = false
var is_crouching: bool = false
var is_jumping: bool = false
var is_falling: bool = false
var is_attacking: bool = false
var is_blocking: bool = false

# --- Animation state list (auto‑generated by plugin) ---
var available_states = [
#ANIMATION_STATES#
]

# --- Timing & cooldowns ---
@export_group("Timing")
@export var attack_duration: float = 0.5
@export var dodge_duration: float = 0.3
@export var jump_prep_duration: float = 1.9
@export var jump_protection_duration: float = 3.0
@export var slide_duration: float = 1.0
@export var slide_cooldown: float = 5.0
@export var slide_speed_multiplier: float = 3.0
var attack_timer: float = 0.0
var dodge_timer: float = 0.0
var is_in_jump_protection: bool = false
var jump_protection_timer: float = 0.0
var is_jump_prepping: bool = false
var jump_prep_timer: float = 0.0
var is_sliding: bool = false
var slide_timer: float = 0.0
var slide_cooldown_timer: float = 0.0
var last_crouch_press_time: float = 0.0

func _ready():
	## Activate the AnimationTree, start on the idle state (or first available),
	## and capture the mouse cursor for look controls.
	if animation_tree:
		animation_tree.active = true
		# Start with idle if available, otherwise use first available state
		if "idle" in available_states:
			state_machine.start("idle")
		elif "crouch_idle" in available_states:
			state_machine.start("crouch_idle")
		elif available_states.size() > 0:
			state_machine.start(available_states[0])
	else:
		push_error("AnimationTree not found! Make sure the path is correct.")
	
	# Lock mouse for gameplay
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _physics_process(delta):
	## Main loop — runs every physics frame.
	## Order matters: timers → input → movement → gravity → jump → animation.
	_handle_timers(delta)
	_handle_input()
	_handle_movement(delta)
	_handle_gravity(delta)
	_handle_jump()
	_handle_jump_prep(delta)
	_update_animations()
	move_and_slide()

func _handle_timers(delta):
	## Decrement all action timers (attack, dodge, slide, slide cooldown).
	## Clears the corresponding is_* flag when a timer expires.
	if attack_timer > 0:
		attack_timer -= delta
		if attack_timer <= 0:
			is_attacking = false
	
	# Dodge timer
	if dodge_timer > 0:
		dodge_timer -= delta
	
	# Slide timer
	if slide_timer > 0:
		slide_timer -= delta
		if slide_timer <= 0:
			is_sliding = false
	
	# Slide cooldown timer
	if slide_cooldown_timer > 0:
		slide_cooldown_timer -= delta

func _handle_input():
	## Poll input actions and set the corresponding state flags.
	## Handles combat (attack, dodge, block), crouching, double‑tap slide
	## detection, and running.
	if Input.is_action_just_pressed("attack") and not is_attacking and is_on_floor():
		is_attacking = true
		attack_timer = attack_duration
	
	if Input.is_action_just_pressed("dodge") and not is_attacking and dodge_timer <= 0:
		dodge_timer = dodge_duration
		_perform_dodge()
	
	# Blocking
	is_blocking = Input.is_action_pressed("block") and not is_attacking and is_on_floor()
	
	# Crouching
	is_crouching = Input.is_action_pressed("crouch") and is_on_floor() and not is_attacking
	
	# Double-tap crouch while running → slide
	if Input.is_action_just_pressed("crouch") and is_running and not is_sliding and slide_cooldown_timer <= 0:
		var now = Time.get_ticks_msec() / 1000.0
		if now - last_crouch_press_time < 0.3:
			is_sliding = true
			slide_timer = slide_duration
			slide_cooldown_timer = slide_cooldown
			is_crouching = true
		last_crouch_press_time = now
	
	# Running
	is_running = Input.is_action_pressed("run") and not is_crouching and not is_attacking

func _handle_movement(delta):
	## Apply velocity based on input direction and current state.
	## Slide overrides normal movement (no steering, fixed forward trajectory).
	## Attacking, blocking, or jump‑prepping locks the character in place.
	## Movement axes can be inverted via invert_move_x / invert_move_z.
	if is_sliding:
		var forward = -transform.basis.z
		velocity.x = forward.x * speed * slide_speed_multiplier
		velocity.z = forward.z * speed * slide_speed_multiplier
		is_moving = true
		return
	
	# Don't move if attacking, blocking, or jump prepping
	if is_attacking or is_blocking or is_jump_prepping:
		velocity.x = move_toward(velocity.x, 0, speed * 2)
		velocity.z = move_toward(velocity.z, 0, speed * 2)
		is_moving = false
		return
	
	var input_dir = Input.get_vector("move_left", "move_right", "move_forward", "move_back")
	var move_x = input_dir.x * (-1.0 if invert_move_x else 1.0)
	var move_z = input_dir.y * (-1.0 if invert_move_z else 1.0)
	var direction = (transform.basis * Vector3(move_x, 0, move_z)).normalized()
	
	# Calculate current speed based on state
	var current_speed = speed
	if is_crouching:
		current_speed *= crouch_speed_multiplier
	elif is_running:
		current_speed *= run_speed_multiplier
	
	if direction != Vector3.ZERO:
		velocity.x = direction.x * current_speed
		velocity.z = direction.z * current_speed
		is_moving = true
	else:
		velocity.x = move_toward(velocity.x, 0, speed)
		velocity.z = move_toward(velocity.z, 0, speed)
		is_moving = false

func _handle_gravity(delta):
	## Apply gravity when airborne, zero out downward velocity on ground.
	if not is_on_floor():
		velocity.y -= gravity * delta
		is_falling = velocity.y < 0
	else:
		is_falling = false
		if velocity.y < 0:
			velocity.y = 0

func _handle_jump():
	## Start jump‑prep wind‑up on jump press (must be on floor, not crouching/attacking).
	## The actual velocity.y is applied in _handle_jump_prep() after the delay.
	if Input.is_action_just_pressed("jump") and is_on_floor() and not is_crouching and not is_attacking:
		if not is_jump_prepping:
			is_jump_prepping = true
			jump_prep_timer = jump_prep_duration
			is_crouching = false
	else:
		is_jumping = false

func _handle_jump_prep(delta):
	## Wait out the prep delay, then apply upward velocity and mark is_jumping.
	if is_jump_prepping:
		jump_prep_timer -= delta
		if jump_prep_timer <= 0:
			velocity.y = jump_force
			is_jumping = true
			is_jump_prepping = false

func _perform_dodge():
	## Launch the character in the input direction at 3× speed for one frame.
	## The dodge animation plays for dodge_duration seconds.
	var input_dir = Input.get_vector("move_left", "move_right", "move_forward", "move_back")
	if input_dir != Vector2.ZERO:
		var dx = input_dir.x * (-1.0 if invert_move_x else 1.0)
		var dz = input_dir.y * (-1.0 if invert_move_z else 1.0)
		var dodge_direction = (transform.basis * Vector3(dx, 0, dz)).normalized()
		velocity.x = dodge_direction.x * speed * 3
		velocity.z = dodge_direction.z * speed * 3

func _update_animations():
	## Drive the AnimationTree state machine based on current flags.
	## Priority order (highest → lowest):
	##   attack > block > dodge > jump‑prep > jump > jump‑prot > fall >
	##   landing > slide > crouch > run > walk > idle
	## Uses was_in_air tracking at the very top for reliable landing detection.
	if not state_machine:
		return
	
	# Track air state every frame (even through early returns) for landing detection
	var previous_was_in_air = was_in_air
	was_in_air = not is_on_floor()
	
	# Get input direction for blend spaces
	var input_dir = Input.get_vector("move_left", "move_right", "move_forward", "move_back")
	
	# Priority: attacking > dodging > jumping > falling > blocking > crouching > moving > idle
	
	# Combat animations
	if is_attacking:
		if "attack_1" in available_states:
			state_machine.travel("attack_1")
		return
	
	if is_blocking and "block" in available_states:
		state_machine.travel("block")
		return
	
	if dodge_timer > 0 and "dodge" in available_states:
		state_machine.travel("dodge")
		return
	
	# Jump prep - play jump start animation while winding up
	if is_jump_prepping:
		if "jump" in available_states and state_machine.get_current_node() != "jump":
			state_machine.travel("jump")
		return
	
	# Aerial animations
	if is_jumping and "jump" in available_states:
		if state_machine.get_current_node() != "jump":
			state_machine.travel("jump")
		is_in_jump_protection = true
		jump_protection_timer = 0.0
		return
	
	# Block aerial transitions while jump protection is active
	# but allow landing if the character reached the ground
	if is_in_jump_protection:
		jump_protection_timer += get_physics_process_delta_time()
		if jump_protection_timer >= jump_protection_duration:
			is_in_jump_protection = false
		elif is_on_floor() and "land" in available_states:
			state_machine.travel("land")
			is_in_jump_protection = false
		else:
			return
	
	if is_falling and "fall" in available_states:
		if state_machine.get_current_node() != "fall":
			state_machine.travel("fall")
		return
	
	# Landing detection - manual control for ground detection
	if "land" in available_states and previous_was_in_air and is_on_floor():
		state_machine.travel("land")
		return
	
	# If still in the air, don't switch to ground animations
	if not is_on_floor():
		return
	
	# Slide animation
	if is_sliding:
		if "slide" in available_states:
			state_machine.travel("slide")
		elif "crouch_blend_space" in available_states:
			state_machine.travel("crouch_blend_space")
			_set_blend_position("crouch_blend_space", Vector2.DOWN)
		else:
			state_machine.travel("crouch_idle" if "crouch_idle" in available_states else "idle")
		return
	
	# Ground movement animations
	if is_crouching:
		if is_moving:
			# Try crouch blend space first
			if "crouch_blend_space" in available_states:
				state_machine.travel("crouch_blend_space")
				_set_blend_position("crouch_blend_space", input_dir)
			else:
				# Use individual crouch animations
				_play_directional_animation("crouch", input_dir)
		else:
			# Crouch idle
			if "crouch_idle" in available_states:
				state_machine.travel("crouch_idle")
	
	elif is_moving:
		if is_running:
			# Try run blend space first
			if "run_blend_space" in available_states:
				state_machine.travel("run_blend_space")
				_set_blend_position("run_blend_space", input_dir)
			else:
				# Use individual run animations
				_play_directional_animation("run", input_dir)
		else:
			# Try walk blend space first
			if "walk_blend_space" in available_states:
				state_machine.travel("walk_blend_space")
				_set_blend_position("walk_blend_space", input_dir)
			else:
				# Use individual walk animations
				_play_directional_animation("walk", input_dir)
	
	else:
		# Idle
		if "idle" in available_states:
			state_machine.travel("idle")

func _set_blend_position(blend_name: String, target: Vector2):
	## Smoothly lerp a blend‑space position toward [param target] instead of
	## snapping instantly. The [param blend_speed] export controls how fast
	## the blend position catches up.
	if not animation_tree:
		return
	var current = animation_tree.get("parameters/" + blend_name + "/blend_position")
	var smooth = current.lerp(target, blend_speed * get_physics_process_delta_time())
	animation_tree.set("parameters/" + blend_name + "/blend_position", smooth)

func _play_directional_animation(movement_type: String, input_dir: Vector2):
	## Fallback for when no blend space exists: picks the closest directional
	## animation clip (e.g. "walk_forward", "run_left") based on the dominant
	## axis of [param input_dir].
	var anim_name = ""
	
	if abs(input_dir.y) > abs(input_dir.x):
		# Forward/backward movement
		if input_dir.y < -0.1:
			anim_name = movement_type + "_forward"
		elif input_dir.y > 0.1:
			anim_name = movement_type + "_backward"
	else:
		# Left/right movement
		if input_dir.x < -0.1:
			anim_name = movement_type + "_left"
		elif input_dir.x > 0.1:
			anim_name = movement_type + "_right"
	
	# Fallback to forward if specific direction not available
	if anim_name == "" or anim_name not in available_states:
		anim_name = movement_type + "_forward"
	
	# Final fallback
	if anim_name not in available_states and movement_type + "_forward" in available_states:
		anim_name = movement_type + "_forward"
	
	if anim_name in available_states:
		state_machine.travel(anim_name)

var was_in_air: bool = false

func _input(event):
	## Handle mouse toggle (Escape) and mouse‑look rotation.
	## Yaw rotates the player node; pitch rotates the Camera3D child (clamped ±90°).
	## Both axes can be inverted via invert_mouse_x / invert_mouse_y.
	if event.is_action_pressed("ui_cancel"):
		if Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		else:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	
	# Mouse look (only when captured)
	if event is InputEventMouseMotion and Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
		var yaw_sign = -1.0 if not invert_mouse_x else 1.0
		rotate_y(yaw_sign * event.relative.x * mouse_sensitivity)
		if camera:
			var pitch_sign = -1.0 if not invert_mouse_y else 1.0
			camera.rotate_x(pitch_sign * event.relative.y * mouse_sensitivity)
			camera.rotation.x = clamp(camera.rotation.x, deg_to_rad(-90), deg_to_rad(90))
	
	# Handle any additional input events here
	if event is InputEventKey and event.pressed:
		match event.keycode:
			KEY_1:
				if "attack_1" in available_states:
					_force_play_animation("attack_1")
			KEY_2:
				if "attack_2" in available_states:
					_force_play_animation("attack_2")
			KEY_3:
				if "attack_3" in available_states:
					_force_play_animation("attack_3")

# Helper functions
func has_animation_state(state_name: String) -> bool:
	## Check if a state name exists in the available_states array.
	return state_name in available_states

func _force_play_animation(state_name: String):
	## Travel to [param state_name] and set the attacking flag with timer.
	if has_animation_state(state_name) and state_machine:
		state_machine.travel(state_name)
		is_attacking = true
		attack_timer = attack_duration

func play_animation(state_name: String):
	## Public helper to travel to any named state. Safe no‑op if state is missing.
	if has_animation_state(state_name) and state_machine:
		state_machine.travel(state_name)

# --- Query helpers ---
func can_attack() -> bool:
	return not is_attacking and is_on_floor()

func can_block() -> bool:
	return not is_attacking and is_on_floor()

func can_dodge() -> bool:
	return dodge_timer <= 0 and not is_attacking

func is_in_air() -> bool:
	return not is_on_floor()

func get_current_animation_state() -> String:
	## Return the name of the currently playing animation state (or "" if unavailable).
	if state_machine:
		return state_machine.get_current_node()
	return ""

func print_current_state():
	## Debug helper — prints current animation state and movement flags to the console.
	print("Current State: ", get_current_animation_state())
	print("Moving: ", is_moving, " | Running: ", is_running, " | Crouching: ", is_crouching)
	print("Jumping: ", is_jumping, " | Falling: ", is_falling)
	print("Attacking: ", is_attacking, " | Blocking: ", is_blocking)
